import os
import re
import logging
from pathlib import Path
from typing import Optional
import yt_dlp

from app.config import settings
from app.services.storage import storage_manager
from app.services.job_store import job_store
from app.services.ffmpeg_utils import get_ffmpeg_location, is_ffmpeg_available

logger = logging.getLogger(__name__)

def parse_quality_height(quality: str) -> Optional[str]:
    """Extract height integer string from quality parameter (e.g. '1080p' -> '1080')."""
    match = re.search(r'(\d+)', str(quality))
    return match.group(1) if match else None

def execute_download(download_job_id: str, url: str, format_type: str, quality: str, ffmpeg_location: Optional[str] = None) -> str:
    """
    Executes yt-dlp download & ffmpeg postprocessing.
    Updates job_store progress and registers resulting file with storage_manager.
    Returns path to downloaded media file.
    """
    job_store.update_job_progress(download_job_id, 5.0, status="processing")
    job_dir = storage_manager.get_job_dir(download_job_id)
    out_template = str(job_dir / "%(title)s.%(ext)s")

    def progress_hook(d):
        if d.get("status") == "downloading":
            total = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
            downloaded = d.get("downloaded_bytes") or 0
            if total > 0:
                pct = 5.0 + (downloaded / total) * 85.0
                job_store.update_job_progress(download_job_id, pct, status="processing")
        elif d.get("status") == "finished":
            job_store.update_job_progress(download_job_id, 95.0, status="processing")

    ydl_opts = {
        "outtmpl": out_template,
        "progress_hooks": [progress_hook],
        "quiet": True,
        "no_warnings": True,
        "nocheckcertificate": True,
    }

    ffmpeg_loc = ffmpeg_location or get_ffmpeg_location()
    if ffmpeg_loc:
        ydl_opts["ffmpeg_location"] = ffmpeg_loc

    has_ffmpeg = is_ffmpeg_available(ffmpeg_loc)

    if format_type.lower() == "audio":
        ydl_opts["format"] = "bestaudio/best"
        if has_ffmpeg:
            bitrate = "192"
            if "kbps" in quality.lower():
                bitrate_match = re.search(r'(\d+)', quality)
                if bitrate_match:
                    bitrate = bitrate_match.group(1)
            ydl_opts["postprocessors"] = [{
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": bitrate,
            }]
    else:
        # Video format selection
        height = parse_quality_height(quality)
        if has_ffmpeg:
            if height:
                ydl_opts["format"] = f"bestvideo[height<={height}][ext=mp4]+bestaudio[ext=m4a]/bestvideo[height<={height}]+bestaudio/best[height<={height}]/best"
            else:
                ydl_opts["format"] = "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
            ydl_opts["merge_output_format"] = "mp4"
        else:
            if height:
                ydl_opts["format"] = f"best[height<={height}][ext=mp4]/best[height<={height}]/best[ext=mp4]/best"
            else:
                ydl_opts["format"] = "best[ext=mp4]/best"

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])

        # Locate the downloaded file in job_dir
        downloaded_files = [f for f in job_dir.glob("*") if f.is_file()]
        if not downloaded_files:
            raise FileNotFoundError("No output file generated by yt-dlp download process.")

        final_file = downloaded_files[0]
        storage_manager.register_file(download_job_id, str(final_file))
        
        file_url = f"{settings.BASE_URL}/api/v1/files/{download_job_id}"
        job_store.set_job_ready(download_job_id, file_url)
        logger.info(f"Job {download_job_id} successfully downloaded to {final_file}")
        return str(final_file)

    except Exception as e:
        err_str = str(e)
        if "ffmpeg not found" in err_str.lower() or "ffprobe and ffmpeg not found" in err_str.lower():
            friendly_err = "Audio conversion / video merging requires ffmpeg. Please install ffmpeg."
            logger.error(f"Download job {download_job_id} failed: {friendly_err}")
            job_store.set_job_failed(download_job_id, friendly_err)
            raise Exception(friendly_err) from e
        else:
            logger.error(f"Download job {download_job_id} failed: {e}", exc_info=True)
            job_store.set_job_failed(download_job_id, err_str)
            raise e
