package com.videodownloader.app.model

data class SubtitleOption(
    val languageCode: String,
    val languageName: String,
    val downloadUrl: String,
    val format: String = "vtt", // e.g. "vtt", "srt"
    val isAutoGenerated: Boolean = false
)
